# Site Info
title: '해리의 데브로그'
tagline: '해리의 데브로그'
description: '프로그래밍을 공부하며 배운점을 정리하고 기록하는 곳입니다'
baseurl: ""
url: https://tothefullest08.github.io/
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
encoding: utf-8

version: 1.0.0

# About/contact
author:
  name: Harry
  description: Harry
  # gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/tothefullest08
    # facebook:  <hide>
    # twitter:   https://twitter.com/Li_Zhihao
    email:     mailto:tothefullest08@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/blog'
  Blog:           
    - '/'
    # - { Categories All: '/blog/categories/' }
    - { TIL: '/blog/categories/#TIL' }
    - { Django: '/blog/categories/#Django' }
    - { Python: '/blog/categories/#python' }
    - { Javascript: '/blog/categories/#Javascript' }
    - { Web: '/blog/categories/#Web' }
    - { Git: '/blog/categories/#Git' }
    - { Algorithm: '/blog/categories/#Algorithm' }
    - { etc: '/blog/categories/#etc' }    
  About:          
    - '/about/'
  Search: 
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# hero:
#   image: /public/img/we_will_be_giants_by_yalestewart.jpg
#   caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-143239251-1' # leave blank if you don't want google analytics
disqus_short_name: 'tothefulles08' # leave blank if you don't want disqus

#Use the following plug-ins
gems:
  - jekyll-paginate